language: go

go:
  # go.mod requires 1.13
  - 1.13.x
  - master

before_install:
  go get -u golang.org/x/lint/golint

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.0

script:
  - make build
