---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "event-consumer-external"
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "event-consumer-external"
subsets:
  - addresses:
      - ip: 10.22.9.235  #change this to your laptop ip address
    ports:
      - port: 27017
