apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-event-sidecar-config
  namespace: openshift-ptp
data:
  # clock state to stay in holdover state in secs
  ptp_holdover_timeout: "5"
  # max offset in nano secs
  ptp_maxoffset_threshold: "99"
  # min offset in nano secs
  ptp_minoffset_threshold: "-99"
  #Example Mount this configmap
  #envFrom:
  #  - configMapRef:
  #     name: cloud-event-sidecar-config