/*
Copyright 2023 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	cloudeventproxyorgv1beta1 "github.com/redhat-cne/cloud-event-proxy/pkg/api/cloud.event.proxy.org/v1beta1"
	versioned "github.com/redhat-cne/cloud-event-proxy/pkg/client/clientset/versioned"
	internalinterfaces "github.com/redhat-cne/cloud-event-proxy/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/redhat-cne/cloud-event-proxy/pkg/client/listers/cloud.event.proxy.org/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CloudEventSubscriberInformer provides access to a shared informer and lister for
// CloudEventSubscribers.
type CloudEventSubscriberInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.CloudEventSubscriberLister
}

type cloudEventSubscriberInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCloudEventSubscriberInformer constructs a new informer for CloudEventSubscriber type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCloudEventSubscriberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCloudEventSubscriberInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCloudEventSubscriberInformer constructs a new informer for CloudEventSubscriber type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCloudEventSubscriberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1beta1().CloudEventSubscribers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1beta1().CloudEventSubscribers(namespace).Watch(context.TODO(), options)
			},
		},
		&cloudeventproxyorgv1beta1.CloudEventSubscriber{},
		resyncPeriod,
		indexers,
	)
}

func (f *cloudEventSubscriberInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCloudEventSubscriberInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cloudEventSubscriberInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudeventproxyorgv1beta1.CloudEventSubscriber{}, f.defaultInformer)
}

func (f *cloudEventSubscriberInformer) Lister() v1beta1.CloudEventSubscriberLister {
	return v1beta1.NewCloudEventSubscriberLister(f.Informer().GetIndexer())
}
