apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consumer-setup-role
  namespace: cloud-events
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consumer-setup-rolebinding
  namespace: cloud-events
subjects:
- kind: ServiceAccount
  name: consumer-sa
  namespace: cloud-events
roleRef:
  kind: Role
  name: consumer-setup-role
  apiGroup: rbac.authorization.k8s.io
