#!/bin/bash

# setup-secrets.sh - Script to set up authentication secrets for cloud-event-consumer
# This script creates the necessary secrets for mTLS authentication using OpenShift Service CA

set -e

NAMESPACE="cloud-events"

echo "Setting up authentication secrets for cloud-event-consumer..."

# Check if we're in an OpenShift cluster
if ! oc get project openshift-service-ca >/dev/null 2>&1; then
    echo "Error: This script requires OpenShift with Service CA operator"
    echo "For generic Kubernetes, please follow the manual certificate generation instructions in auth/certificate-example.md"
    exit 1
fi

echo "✓ OpenShift Service CA detected"

# Wait for the Service CA ConfigMap to be injected
echo "Waiting for Service CA to inject CA bundle into ConfigMap..."
TIMEOUT=60
COUNT=0
while [ $COUNT -lt $TIMEOUT ]; do
    if oc get configmap server-ca-bundle-configmap -n $NAMESPACE -o jsonpath='{.data.service-ca\.crt}' 2>/dev/null | grep -q "BEGIN CERTIFICATE"; then
        echo "✓ Service CA bundle found"
        break
    fi
    echo "Waiting for Service CA to inject CA bundle... ($COUNT/$TIMEOUT)"
    sleep 2
    COUNT=$((COUNT + 1))
done

if [ $COUNT -eq $TIMEOUT ]; then
    echo "Error: Timeout waiting for Service CA to inject CA bundle"
    echo "Please check that the ConfigMap server-ca-bundle-configmap exists and has the annotation service.beta.openshift.io/inject-cabundle: 'true'"
    exit 1
fi

# Extract the CA certificate and create the secret
echo "Creating server-ca-bundle secret..."
CA_CERT=$(oc get configmap server-ca-bundle-configmap -n $NAMESPACE -o jsonpath='{.data.service-ca\.crt}')

# Create the server-ca-bundle secret
oc create secret generic server-ca-bundle \
  --from-literal=service-ca.crt="$CA_CERT" \
  --namespace=$NAMESPACE \
  --dry-run=client -o yaml | oc apply -f -

echo "✓ server-ca-bundle secret created"

# Wait for the client certificate to be generated by Service CA
echo "Waiting for Service CA to generate client certificate..."
COUNT=0
while [ $COUNT -lt $TIMEOUT ]; do
    if oc get secret consumer-client-certs -n $NAMESPACE >/dev/null 2>&1; then
        echo "✓ consumer-client-certs secret found"
        break
    fi
    echo "Waiting for Service CA to generate client certificate... ($COUNT/$TIMEOUT)"
    sleep 2
    COUNT=$((COUNT + 1))
done

if [ $COUNT -eq $TIMEOUT ]; then
    echo "Error: Timeout waiting for Service CA to generate client certificate"
    echo "Please check that the Service consumer-client-service exists and has the annotation service.beta.openshift.io/serving-cert-secret-name: consumer-client-certs"
    exit 1
fi

echo "✓ All authentication secrets are ready"
echo ""
echo "Authentication setup completed successfully!"
echo "The following secrets have been created in namespace '$NAMESPACE':"
echo "  - server-ca-bundle: Contains the Service CA certificate"
echo "  - consumer-client-certs: Contains the client TLS certificate (auto-generated by Service CA)"
echo ""
echo "The consumer pod should now be able to start with mTLS authentication enabled."
