apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-account.yaml
- service.yaml
- consumer.yaml
replicas:
- count: 1
  name: cloud-consumer-deployment
images:
- name: cloud-event-consumer
  newName: quay.io/redhat-cne/cloud-event-consumer
  newTag: latest
