# We only build consumer images for main (label: latest) and release-4.18 (label: 4.18) branches.
# 4.18 consumer is the last version to support v1 events, which is used for 4.18 and earlier releases.
# For 4.19+ releases (v2 events only) we always use main branch for consumer.
name: Build and Push Consumer Image
on:
  push:
    branches: [ main, release-4.18 ]
env:
  VERSION: ${{ github.ref_name == 'main' && 'latest' || github.ref_name == 'release-4.18' && '4.18' }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
    steps:
      - name: Debug
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Quay.io
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and Push
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: examples/consumer.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          # Disable attestations
          provenance: false
          tags: |
            quay.io/redhat-cne/cloud-event-consumer:${{ env.VERSION }}-${{ matrix.arch }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
      - name: Log in to Quay.io
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Create Multi-Arch Manifest List
        if: ${{ github.repository_owner == 'redhat-cne' }}
        run: |
          docker manifest create \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.VERSION }} \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.VERSION }}-amd64 \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.VERSION }}-arm64
          docker manifest push quay.io/redhat-cne/cloud-event-consumer:${{ env.VERSION }}
