name: Build and Push Consumer Image
on:
  push:
    branches: [ consumer-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and Push
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: examples/consumer.Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.repository_owner == 'redhat-cne' }}
          tags: |
            quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }}-${{ matrix.arch }}
            quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: build
    env:
      BRANCH_SANITIZED: ${{ needs.build.outputs.BRANCH_SANITIZED }}
    steps:
      - name: Log in to Quay.io
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Create Multi-Arch Manifest List
        if: ${{ github.repository_owner == 'redhat-cne' }}
        run: |
          docker manifest create \
            quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }} \
            quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }}-amd64 \
            quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }}-arm64
          docker manifest push quay.io/redhat-cne/cloud-event-consumer:${{ github.ref_name }}
