name: Build and Push Consumer Image
on:
  push:
    branches: [ consumer-test ]
  pull_request:
    branches: [ consumer-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
    steps:
      - name: Sanitize branch name
        id: sanitize
        run: |
          SANITIZED_BRANCH="${GITHUB_REF_NAME//\//-}"
          echo "BRANCH_SANITIZED=$SANITIZED_BRANCH" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Secrets (Do NOT expose actual secret values)
        run: |
          echo "1 QUAY_ROBOT_USERNAME is set: ${{ secrets.QUAY_ROBOT_USERNAME != '' }}"
          echo "QUAY_ROBOT_TOKEN is set: ${{ secrets.QUAY_ROBOT_TOKEN != '' }}"
          echo ${{ secrets.QUAY_ROBOT_USERNAME }}

      - name: Log in to Quay.io
        #if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'redhat-cne' }}
        #if: ${{ github.ref == 'refs/heads/consumer-test' && github.repository_owner == 'redhat-cne' }}
        if: ${{ github.repository_owner == 'redhat-cne' }}
        #if: ${{ github.ref == 'refs/pull/446/merge' && github.repository_owner == 'redhat-cne' }}
        #if: ${{ github.repository == 'redhat-cne/cloud-event-proxy' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: DZK debug
        run: |
          echo ${{ github.ref }}

      - name: Build and Push
        # if: ${{ github.ref == 'refs/heads/consumer-test' && github.repository_owner == 'redhat-cne' }}
        if: ${{ github.repository_owner == 'redhat-cne' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: examples/consumer.Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.repository_owner == 'redhat-cne' }}
          tags: |
            quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-${{ matrix.arch }}-DZK
            quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-DZK

  create-manifest:
    runs-on: ubuntu-latest
    needs: build
    env:
      BRANCH_SANITIZED: ${{ needs.build.outputs.BRANCH_SANITIZED }}
    steps:

      - name: Debug Secrets (Do NOT expose actual secret values)
        run: |
          echo "1 QUAY_ROBOT_USERNAME is set: ${{ secrets.QUAY_ROBOT_USERNAME != '' }}"
          echo "QUAY_ROBOT_TOKEN is set: ${{ secrets.QUAY_ROBOT_TOKEN != '' }}"
          echo ${{ secrets.QUAY_ROBOT_USERNAME }}

      - name: Log in to Quay.io
        #if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'redhat-cne' }}
        if: ${{ github.repository_owner == 'redhat-cne' }}
        #if: ${{ github.ref == 'refs/heads/consumer-test' && github.repository_owner == 'redhat-cne' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Create Multi-Arch Manifest List
        # if: ${{ github.ref == 'refs/heads/consumer-test' && github.repository_owner == 'redhat-cne' }}
        if: ${{ github.repository_owner == 'redhat-cne' }}
        run: |
          docker manifest create \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-DZK \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-amd64-DZK \
            quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-arm64-DZK

          docker manifest push quay.io/redhat-cne/cloud-event-consumer:${{ env.BRANCH_SANITIZED }}-DZK
